### ISSUE TITLE
Sonar plugins download from Codehaus fails

### ISSUE THREAD

**Issue by bbaassssiiee** [bbaassssiiee/sonar#1]
All Codehaus services will be terminated progressively until May 17th 2015
https://www.codehaus.org/termination.html

**Comment by bbaassssiiee** [comment]
SonarQube plugins now downloaded from new location.

**Comment by repli007** [comment]
Could you advise what is a new location?

**Comment by bbaassssiiee** [comment]
http://dist.sonarsource.com/oss/org/codehaus/sonar-plugins/sonar-ldap-plugin/1.4/sonar-ldap-plugin-1.4.jar
    http://dist.sonarsource.com/oss/org/codehaus/sonar-plugins/sonar-jira-plugin/1.2/sonar-jira-plugin-1.2.jar'  
    http://dist.sonarsource.com/oss/org/codehaus/sonar-plugins/java/sonar-java-plugin/2.5.1/sonar-java-plugin-2.5.1.jar
    http://dist.sonarsource.com/oss/org/codehaus/sonar-plugins/javascript/sonar-javascript-plugin/2.2/sonar-javascript-plugin-2.2.jar
    http://dist.sonarsource.com/oss/org/codehaus/sonar-plugins/python/sonar-python-plugin/1.3/sonar-python-plugin-1.3.jar
    http://dist.sonarsource.com/oss/org/codehaus/sonar-plugins/xml/sonar-xml-plugin/1.2/sonar-xml-plugin-1.2.jar
    http://dist.sonarsource.com/oss/org/codehaus/sonar-plugins/android/sonar-android-plugin/1.0/sonar-android-plugin-1.0.jar
    http://dist.sonarsource.com/oss/org/codehaus/sonar-plugins/java/sonar-checkstyle-plugin/2.1.1/sonar-checkstyle-plugin-2.1.1.jar
    http://dist.sonarsource.com/oss/org/codehaus/sonar-plugins/sonar-cobertura-plugin/1.6.3/sonar-cobertura-plugin-1.6.3.jar
    http://dist.sonarsource.com/oss/org/codehaus/sonar-plugins/java/sonar-findbugs-plugin/3.1/sonar-findbugs-plugin-3.1.jar
    http://dist.sonarsource.com/oss/org/codehaus/sonar-plugins/sonar-build-breaker-plugin/1.1/sonar-build-breaker-plugin-1.1.jar
    http://dist.sonarsource.com/oss/org/codehaus/sonar-plugins/jmeter/sonar-jmeter-plugin/0.2/sonar-jmeter-plugin-0.2.jar
    http://dist.sonarsource.com/oss/org/codehaus/sonar-plugins/sonar-motion-chart-plugin/1.7/sonar-motion-chart-plugin-1.7.jar
    http://dist.sonarsource.com/oss/org/codehaus/sonar-plugins/sonar-quality-index-plugin/1.1.3/sonar-quality-index-plugin-1.1.3.jar
    http://dist.sonarsource.com/oss/org/codehaus/sonar-plugins/sonar-technicaldebt-plugin/1.2.1/sonar-technicaldebt-plugin-1.2.1.jar
    http://dist.sonarsource.com/oss/org/codehaus/sonar-plugins/sonar-timeline-plugin/1.4/sonar-timeline-plugin-1.4.jar
    http://dist.sonarsource.com/oss/org/codehaus/sonar-plugins/sonar-useless-code-tracker-plugin/1.0/sonar-useless-code-tracker-plugin-1.0.jar
